version: '3.7'

services:
  postgres-db-test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: database_dev
      POSTGRES_USER: database_dev
      POSTGRES_DB: podcodar-platform
      PGPORT: 5430
    ports:
      - 5430:5430
    container_name: postgres-db-test

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - STAGE=test
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3001:3001
    command: >
      sh -c "NODE_ENV=test STAGE=test yarn sequelize-cli db:migrate
      && yarn run:watch"
    container_name: podcodar-app-test
    depends_on:
      - postgres-db-test
