name: CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Iniciando CI/CD...
        run: echo "Iniciando execução do pipeline de CI/CD..."

      - name: Executando CI...
        run: |
          cd client
          yarn install
          yarn test

      - name: Execudando CD...
        run: |
          git init
          git remote
          git remote add client-repository git@github.com:Victorams/podcodar-client.git
          git remote
          git push client-repository main
