name: CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Starting
        run: echo "Iniciando execução do pipeline de CI/CD..."

      - name: Run a multi-line script
        run: |
          echo "Executando testes..."
          cd client
          yarn test
