name: CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Iniciando CI/CD...
        run: echo "Iniciando execução do pipeline de CI/CD..."

      - name: Executando CICD...
        run: |
          cd client
          yarn install
          yarn test
